dist: trusty

git:
  depth: 1

language: cpp

compiler:
 - gcc

branches:
  only:
    - master

before_install:
 - pwd
 - sudo add-apt-repository -y "deb https://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
 - sudo apt-get update -y -qq
 - sudo apt-get install -qq libboost-wave-dev libboost-system-dev libboost-filesystem-dev libboost-thread-dev
 - sudo apt-get install -qq libbullet-dev libbullet-extras-dev
 - sudo apt-get install -qq libopenal-dev
 - sudo apt-get install -qq libenet-dev libvorbisfile3 libogg-dev libvorbis-dev
 - sudo apt-get install -qq libogre-1.9-dev
 - sudo apt-get install -qq libmygui-dev
 - sudo apt-get install -qq libegl1-mesa-dev libgles2-mesa-dev  # workaround https://github.com/travis-ci/travis-ci/issues/9065
 - sudo apt-get install -qq libsdl2-dev

before_script:
 - mkdir build
 - cd build
 - cmake ..

script:
 - make -j2

notifications:
  irc:
    channels:
      - "chat.freenode.net#stuntrally"
    on_success: never
    on_failure: never
